### ISSUE TITLE
Can't create a station on the site

### ISSUE THREAD

**Issue by scalda** [Tysonpower/starlinkstatus#10]
HI,

I seem to be having trouble creating a station via your site, I have an account, API key and also have the client software running thanks to the native windows install. 

But for the life of me, i can't create a station, I go to my dash and click the create a station button, asks me if I want to create another station so click ok but nothing happens after that

![image](https://user-images.githubusercontent.com/1837979/140626049-475d316a-d1ca-4611-87cd-9b3597143578.png)
![image](https://user-images.githubusercontent.com/1837979/140626054-9390d078-b1b0-42d1-8922-90e5344ed840.png)

i'm not sure what I'm doing wrong so thought i would raise an issue and see if i can get some help

thanks in advance

**Comment by scalda** [comment]
ok looks like i have a station on the map now but not in the right place, but still nothing in my dash
![image](https://user-images.githubusercontent.com/1837979/140641250-9294e03f-903b-4972-80a7-9e709dd61e81.png)

**Comment by Tysonpower** [comment]
Looks like a Bug, will look into it asap

**Comment by scalda** [comment]
> Looks like a Bug, will look into it asap

Thank you very much,

**Comment by Tysonpower** [comment]
Should be fixed, you can see the Stations now...i had a code mixup sadly, will need to remove some Bugs in the next hours from other parts of the site.

**Comment by scalda** [comment]
Yes i can see it in the dash now thank you very much

**Comment by Tysonpower** [comment]
hope you don't have like 10 stations now xD Sorry for that, if you need any help you can send me a mail as well to support@starlinkstatus.space :)
