### ISSUE TITLE
error with docker-compose command

### ISSUE THREAD

**Issue by nswfugitive** [Tysonpower/starlinkstatus#13]
Hi - getting the following errors when trying to run.

pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker-compose up -d
Building starlinkstatus
Sending build context to Docker daemon  4.608kB
Step 1/9 : FROM alpine:latest
 ---> 78571b13081b
Step 2/9 : RUN apk update && apk add curl bash go
 ---> Running in ff2ea009d6a0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory
3069449104:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069449104:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069449104:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069449104:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3069449104:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory
2 errors; 14 distinct packages available
The command '/bin/sh -c apk update && apk add curl bash go' returned a non-zero code: 2
ERROR: Service 'starlinkstatus' failed to build : Build failed

**Comment by Tysonpower** [comment]
Looks like you don't get a connection to the base linux of the docker container. Try again later, otherwise:

@sq5t any idea?

**Comment by sq5t** [comment]
@Tysonpower @nswfugitive problem was with docker hub registry, it happens from time to time so now it can be build on Raspberry Pi. But when i've tried to build docker image a have found bug that speedtest binary was downloaded only for x86_64, now (PR 15) it's platform independent.
So @nswfugitive when @Tysonpower will accept my PR to branch master than you can try build image once again.

**Comment by Tysonpower** [comment]
@nswfugitive please pull/clone the repo again and test it.

**Comment by Tysonpower** [comment]
please try to ping the alpine linux dl server:

`ping dl-cdn.alpinelinux.org`

if this doesen't work, try and use the google DNS Server 8.8.8.8 or 1.1.1.1 from cluudflare.

`nameserver 1.1.1.1`

if you can ping the server after that please restart docker and try again.

**Comment by sq5t** [comment]
@nswfugitive also remove docker images with command:
`docker system prune -af`
because sometimes docker cache can cache errors. After that rebuild docker image once again. Also you can use:
`docker-compose build --no-cache` but use this with caution because `--no-cache` doesn't really block using cache as we would think.
If problem still exists do commands below and share with us output:
```
docker ps
docker images ls
docker system prune -af
docker images ls
docker-compose build
```

**Comment by nswfugitive** [comment]
nameserver is not a command on my pi. ping worked fine.

Fewer errors using the build -no-cache option
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker system prune -af
Deleted Containers:
9381f61e1bb0306e5706f6cc3b49c13a5b64ca38f11134f3c11a7d639872db9b

Deleted Images:
untagged: alpine:latest
untagged: alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
deleted: sha256:78571b13081b3f0e2737073f044b9b37aae887b4196f673fdd0dc03fa4a1b7bc
deleted: sha256:db96a9ccbbd6f5e197028662fb1e006f61da6a60abd2cdec9648dc7699eb61a9

Total reclaimed space: 3.814MB
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker-compose build --no-cache
Building starlinkstatus
Sending build context to Docker daemon  4.608kB
Step 1/8 : FROM alpine:latest
latest: Pulling from library/alpine
5480d2ca1740: Pull complete 
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
 ---> 78571b13081b
Step 2/8 : RUN apk update && apk add curl bash go
 ---> Running in 62868705b680
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/armv7/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory
2 errors; 14 distinct packages available
The command '/bin/sh -c apk update && apk add curl bash go' returned a non-zero code: 2
ERROR: Service 'starlinkstatus' failed to build : Build failed
--------------------------------------------------------------------------------------------------------

Here is the output from the commands requested:

pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker ps 
CONTAINER ID   IMAGE                                          COMMAND                  CREATED       STATUS      PORTS                                                           NAMES
6c50cb00dcff   portainer/portainer-ce:latest                  "/portainer"             11 days ago   Up 9 days   8000/tcp, 9443/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp   portainer
1e319b1bc481   ghcr.io/danopstech/prometheus:latest           "/bin/prometheus --c…"   11 days ago   Up 9 days   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp                       starlink-main_prometheus_1
edfca69cd23b   ghcr.io/danopstech/blackbox_exporter:latest    "/bin/blackbox_expor…"   11 days ago   Up 9 days   0.0.0.0:9115->9115/tcp, :::9115->9115/tcp                       starlink-main_blackbox_1
18998a4d20ea   ghcr.io/danopstech/speedtest_exporter:latest   "/speedtest_exporter"    11 days ago   Up 9 days   0.0.0.0:9092->9090/tcp, :::9092->9090/tcp                       starlink-main_speedtest_exporter_1
0c61d7324dde   ghcr.io/danopstech/starlink_exporter:latest    "/starlink_exporter"     11 days ago   Up 9 days   0.0.0.0:9817->9817/tcp, :::9817->9817/tcp                       starlink-main_starlink_exporter_1
690f0f9fa511   ghcr.io/danopstech/grafana:latest              "/run.sh"                11 days ago   Up 9 days   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                       starlink-main_grafana_1
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker images ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker system prune -af
Deleted Containers:
62868705b680e2ee309693fdbbc57d002a4a37d86d1f95494af177aa52c7c073

Deleted Images:
untagged: alpine:latest
untagged: alpine@sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
deleted: sha256:78571b13081b3f0e2737073f044b9b37aae887b4196f673fdd0dc03fa4a1b7bc
deleted: sha256:db96a9ccbbd6f5e197028662fb1e006f61da6a60abd2cdec9648dc7699eb61a9

Total reclaimed space: 3.814MB
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker images ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ docker-compose build
Building starlinkstatus
Sending build context to Docker daemon  4.608kB
Step 1/8 : FROM alpine:latest
latest: Pulling from library/alpine
5480d2ca1740: Pull complete 
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
 ---> 78571b13081b
Step 2/8 : RUN apk update && apk add curl bash go
 ---> Running in c21ad653b383
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/armv7/APKINDEX.tar.gz
3070063504:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070063504:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070063504:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070063504:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070063504:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/armv7/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory
2 errors; 14 distinct packages available
The command '/bin/sh -c apk update && apk add curl bash go' returned a non-zero code: 2
ERROR: Service 'starlinkstatus' failed to build : Build failed

**Comment by sq5t** [comment]
@nswfugitive it's look like problem with libseccomp2 according to this bug [https://github.com/alpinelinux/docker-alpine/issues/110](https://github.com/alpinelinux/docker-alpine/issues/110). Please check with command `apt-cache policy libseccomp2` what version of libseccomp2 you've got.
Second problem that i've found is that mechanism to download speedtest for required architecture is wrong because on RPi 4 with 64 bit OS i have with `uname -m` aarch64 that is correct for downloading client but for RPi that reports with `uname -m` armv7l it's not correct. Because i didn't have time on this weekend and next free evening i'll have for two days please wait and i'll fix it once for all. This time please take to see bug that i've linked. To check version of libseccomp2 you can use command `apt-cache policy libseccomp2`.

**Comment by nswfugitive** [comment]
pi@raspi4-8gb-argon:~/Downloads/starlinkstatus-main/docker $ apt-cache policy libseccomp2
libseccomp2:
  Installed: 2.3.3-4
  Candidate: 2.3.3-4
  Version table:
 *** 2.3.3-4 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status

**Comment by nswfugitive** [comment]
Looks like the the Pi OS isn't upgrading to the 2.4 version - my Pi is up to date.
