### ISSUE TITLE
starlink

### ISSUE THREAD

**Issue by sparkdad** [Tysonpower/starlinkstatus#14]
during install, requests change ip to starlink, Space Exploration Technologies is my IP, isn't this starlink?

**Comment by Tysonpower** [comment]
@tevslin we did have this before, didn't you fix this in your widnows software? I thought so.

**Comment by tevslin** [comment]
I look only for “Starlink” as ISP so it is a problem with the windows code if a different name is returned in different places. Is there a list of possible names or should I just drop this test?

 

Thank you.

 

Tom

**Comment by tevslin** [comment]
working on this

**Comment by tevslin** [comment]
pull request pending for fix

**Comment by Tysonpower** [comment]
thank you! Just merged your pull request :)
