### ISSUE TITLE
Front page statistics underestimated because of inactive stations?

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [Tysonpower/starlinkstatus#2]
The statistics at the top of the front page show speeds around ~40 Mbit/s in the Download and ~9 Mbit/s in the Upload. The graph below shows much higher Download AVG speeds **if** zero values are neglected. See also screenshot.

Probably the numbers at the top also consider measurements which report zero bandwidth (at the beginning of measurements in March/April/May and recently no active users in France), which leads to rather poor numbers at the top of the front page.

I'd suggest to discard reports with zero bandwidth and/or inactive users...

![Screenshot from 2021-07-14 22-05-19](https://user-images.githubusercontent.com/60349884/125687397-aab4931f-dbec-4b32-9a62-5c74ee55c575.png)

**Comment by Tysonpower** [comment]
The Graphs Show the AVG, the big number above that show the 95th percentile NOT the AVG.
For the EU for example the AVG (right to the big Number) shows 178Mbit/s, all calculations are done with a filter on failed tests btw :)

I maybe change the big Number to AVG tho, many People are a bit confused with the 95th percentile.

**Comment by joergdeutschmann-i7** [comment]
Ah thanks, I missed that. Could it be that for earlier versions the average was used? I somehow remember the big number showing higher values (maybe average). Anyway, +1 to use the median or average for the big number...

**Comment by Tysonpower** [comment]
Changed the Big Number to AVG, 95th is now between Max and Min to the right
