### ISSUE TITLE
[Windows] Important file missing

### ISSUE THREAD

**Issue by sinnx3** [Tysonpower/starlinkstatus#20]
@tevslin @Tysonpower 

Note: No anti-virus program was involved resulting in the missing file.

![image](https://user-images.githubusercontent.com/3137441/153964544-dc7400fc-5c8e-4b31-81a0-bafde3adad55.png)

**Comment by tevslin** [comment]
The file schedulestarlinkinkstatus,exe is in exes.zip which the screen capture shows did download and unzip properly. It is extremely likely that a virus checker DID remove this file to "protect" you between the unzip and the invocation,

**Comment by sinnx3** [comment]
> The file schedulestarlinkinkstatus,exe is in exes.zip which the screen capture shows did download and unzip properly. It is extremely likely that a virus checker DID remove this file to "protect" you between the unzip and the invocation,

I made an exclusion to the folder in windows defender and re-ran the powershell script, the issue still remained.

I ended up downloading and running the files manually from the repo.

**Comment by tevslin** [comment]
As you can see from your successful download, the fileis really there. either defender or some other anti-virus program is most likely removing it right after it is unzipped, Thank you for taking the time to work with this.

**Comment by Tysonpower** [comment]
can this be closed?

**Comment by tevslin** [comment]
I think so. Thanks
