### ISSUE TITLE
bring windows version uptodate

### ISSUE THREAD

**Issue by tevslin** [Tysonpower/starlinkstatus#21]
what needs to be done, if anything, besides version number, retry curl to get ping servers, and removal of unsupported api?

**Comment by Tysonpower** [comment]
i don't think you really need to make an update, but if so it would be the three things you mentioned above. I don't even know if the curl stuff is a problem on windows.

**Comment by tevslin** [comment]
If I don’t update, won’t people get a message asking them to update their clients? AFIK the curl stuff is not a problem on windows.

 

Thanks.

**Comment by Tysonpower** [comment]
yeah, was thinking about that as well, would be great if you could make a quick update then :)

**Comment by tevslin** [comment]
will create pull request for new version which transmits version number. already wasn't doing failed curl . but should there be separate ID somehow of Windows client?

**Comment by Tysonpower** [comment]
yeah just add win to the Version. so it would be version 1.2win in this case.

**Comment by tevslin** [comment]
Adding “win” seems to break whatever is parsing the send to the website. Results in a “key not valid”

**Comment by Tysonpower** [comment]
@tevslin backend is fine, i had to add " around the version variable  so it is a string in the json data, think this will be your Problem as well.

After this my Linux script also can send 1.2win if it want's :)

See my testaccount:
https://starlinkstatus.space/stations/1

**Comment by Tysonpower** [comment]
merged :)
