### ISSUE TITLE
SSL Errors on starlinkstatus.space

### ISSUE THREAD

**Issue by consentfactory** [Tysonpower/starlinkstatus#23]
Going to starlinkstatus.space results in SSL errors.

![image](https://user-images.githubusercontent.com/11437306/156047998-2d75cd72-41f4-4e52-9a9e-616b4f83d363.png)

Appears to be because the root CA that the cert was generated under has expired.

Resolution: generate new certificate from your CA for the website. 

Details:
https://www.ssllabs.com/ssltest/analyze.html?d=starlinkstatus.space&latest

![image](https://user-images.githubusercontent.com/11437306/156048326-599e6042-9d93-46a9-addf-b5d49f137a1c.png)

**Comment by Tysonpower** [comment]
This is not an error on our website, all certs you get from the servers are valid, the only problem is that you have a self signed cert on your computer it seems (see your own screenshot). I just opened the link you posted from ssllabs, all is green and happy on there.

I recommend:
- clear your cert cache / website data
- make sure your pc doesen't have any https scanner on it ( used by cooperations for example to restrict access to websites on work notebooks)

**Comment by consentfactory** [comment]
Yup. You're totally right. Apologies for that!

I decided to try Malwarebytes recently and it looks like it was redirecting that and listed your site as compromised. 

Guess I'm removing Malwarebytes now...

**Comment by Tysonpower** [comment]
> Yup. You're totally right. Apologies for that!
> 
> I decided to try Malwarebytes recently and it looks like it was redirecting that and listed your site as compromised.
> 
> Guess I'm removing Malwarebytes now...

yeah...i used malewarebytes in the past and it was great a few years ago...but now it acts up like an other antivirus i don't longer use :)

**Comment by consentfactory** [comment]
Yeah, if I wasn't forced into Windows, I would be trying doing such shenanigans. 

Great tool and website (now that I can see it, lol). Passing this along to a colleague that has Starlink. 

Cheers.
