### ISSUE TITLE
Connection error after "retesting speedtest..."

### ISSUE THREAD

**Issue by ukasuviok** [Tysonpower/starlinkstatus#24]
Script output below:

C:\users\*****\documents\StarlinkScripts already exists.
VERBOSE: GET https://raw.githubusercontent.com/Tysonpower/starlinkstatus/main/windowsinstall/messages.json with 0-byte payload
VERBOSE: received 1086-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/Tysonpower/starlinkstatus/main/windowsinstall/Starlinkstatus_client.ps1 with 0-byte payload
VERBOSE: received 3713-byte response of content type text/plain; charset=utf-8
VERBOSE: GET https://raw.githubusercontent.com/Tysonpower/starlinkstatus/main/windowsinstall/starlinkstatusstarter.ps1 with 0-byte payload
VERBOSE: received 309-byte response of content type text/plain; charset=utf-8
https://github.com/tevslin/Starlink-Statuspage-Clients/raw/main/exes.zip downloaded
exes.zip unzipped
https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-win64.zip downloaded
ookla-speedtest-1.0.0-win64.zip unzipped
testing speedtest...
retesting speedtest...
{"type":"log","timestamp":"2022-03-03T14:36:42Z","message":"Error: [0] Cannot open socket: ","level":"error"}
speedtest failure
{"type":"log","timestamp":"2022-03-03T14:39:25Z","message":"Error: [0] Cannot open socket: ","level":"error"}
{"type":"log","timestamp":"2022-03-03T14:43:01Z","message":"Error: [0] Cannot open socket: ","level":"error"}
error
Cannot write: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host ...
speedtest failure
Latency test failed for both TCP, and no HTTP URL available.
{"type":"log","timestamp":"2022-03-03T14:45:56Z","message":"Error: [0] Cannot open socket: ","level":"error"}
{"type":"log","timestamp":"2022-03-03T14:47:03Z","message":"Error: [0] Cannot open socket: ","level":"error"}
speedtest failure
Latency test failed for both TCP, and no HTTP URL available.

**Comment by Tysonpower** [comment]
@ukasuviok What did you do to fix this error?
