### ISSUE TITLE
Win10 install: Please update your Client!

### ISSUE THREAD

**Issue by f205v** [Tysonpower/starlinkstatus#26]
I installed your software on my Win10 machine.
Since a few days, when checking my status page: https://starlinkstatus.space/stations/500
it tells me: "Please update your Client!"
I'm not very technically savvy, can you please give some instructions on how to update the client in my Win10 install?
Thank you very much!

**Comment by Tysonpower** [comment]
please use email next time instead of an issue :)

You can update by just installing it again like you did before by following the instructions in the readme. If this doesen't work you could try and remove it from your windows machine and install it again.

regards,
Manuel
