### ISSUE TITLE
Retesting Speedtest Fails on Win 11

### ISSUE THREAD

**Issue by Capt-Ed** [Tysonpower/starlinkstatus#28]
When I tried to install the "Retesting Speedtest" fails after waiting for several minutes.

**Comment by Capt-Ed** [comment]
it never asked me for the API key.

**Comment by Tysonpower** [comment]
did you try to run the installer as an administrator?

**Comment by Capt-Ed** [comment]
yes followed the instructions exactly PS run as administrator. Here is the error message I received:
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
                                                                                Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows                                                                                                                                                       PS C:\WINDOWS\system32> powershell.exe -noprofile -executionpolicy bypass -file "D:\My_Data\Data\6-Financial\Boat Serenity\Starlink\statusupload\Install.ps1"   C:\users\ed\documents\StarlinkScripts already exists.
VERBOSE: GET with 0-byte payload
VERBOSE: received 1086-byte response of content type text/plain; charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received 3713-byte response of content type text/plain; charset=utf-8
VERBOSE: GET with 0-byte payload
VERBOSE: received 309-byte response of content type text/plain; charset=utf-8
https://github.com/tevslin/Starlink-Statuspage-Clients/raw/main/exes.zip downloaded
exes.zip unzipped
https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-win64.zip downloadedookla-speedtest-1.0.0-win64.zip unzipped
testing speedtest...
retesting speedtest...
{"type":"log","timestamp":"2022-04-30T13:22:45Z","message":"Error: [10060] Cannot read from socket: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\n","level":"error"}
{"type":"log","timestamp":"2022-04-30T13:28:17Z","message":"Error: [10060] Cannot read from socket: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.\r\n","level":"error"}
{"type":"log","timestamp":"2022-04-30T13:29:29Z","message":"Error: [0] Cannot open socket: ","level":"error"}

**Comment by Tysonpower** [comment]
@tevslin Do you have any idea? i'm not the biggest windows expert to be honest.

**Comment by Capt-Ed** [comment]
It looks like a port it needs is being blocked, but I don't understand how it works the first time and then fails on the second. What is it doing different the second time?

**Comment by tevslin** [comment]
I’ll look but don’t have windows 11 to test with. I agree that 2d time should be like the first.
