### ISSUE TITLE
Error during build grpcurl

### ISSUE THREAD

**Issue by p2rjp0** [Tysonpower/starlinkstatus#3]
Installed golang using apt install.
go get github does a lot and compiles a lot but finishes giving the following error (below is from re-run...):-
go get github.com/fullstorydev/grpcurl/...
# google.golang.org/grpc/credentials
go/src/google.golang.org/grpc/credentials/tls.go:233:2: undefined: tls.TLS_AES_128_GCM_SHA256
go/src/google.golang.org/grpc/credentials/tls.go:234:2: undefined: tls.TLS_AES_256_GCM_SHA384
go/src/google.golang.org/grpc/credentials/tls.go:235:2: undefined: tls.TLS_CHACHA20_POLY1305_SHA256
# golang.org/x/net/http2
go/src/golang.org/x/net/http2/client_conn_pool.go:305:6: undefined: errors.Is
go/src/golang.org/x/net/http2/server.go:234:72: undefined: tls.VersionTLS13

Regards

**Comment by Tysonpower** [comment]
I think apt gave you an old version of go, please install it as mentioned in the Readme with the following instructions:

https://golang.org/doc/install

**Comment by p2rjp0** [comment]
That seems to have fixed it (Needed GUI to get through instructions...).
Gave informational message while running GET 
 
        go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

Regards
Randall
