### ISSUE TITLE
Integration into Home Assistant

### ISSUE THREAD

**Issue by LordNex** [Tysonpower/starlinkstatus#31]
Don't know if any of you use Home Assistant but it's the defaco goto for Home Automation in Open Source. All of its third party apps use GitHub and docker to run. 

This would be really could I'd you could find a way to make it an install and run on there. I know there's a lot of people who would use it.

**Comment by Tysonpower** [comment]
Yeah i use Home Assistant myself, maybe i will have a look if i can integrate it as an app, but i think it could get quite complicated doing so.

**Comment by LordNex** [comment]
Maybe if you just based it off of what data you can get from 192.168.100.1 or dishy.Starlink.com. Wouldn’t need everything. Just the main data

Benjamin T Powers

On May 8, 2022, at 11:21 AM, Tysonpower ***@***.***> wrote:

﻿

Yeah i use Home Assistant myself, maybe i will have a look if i can integrate it as an app, but i think it could get quite complicated doing so.

**Comment by LordNex** [comment]
They let you run their MSP software free which adds an API. I was able to integrate that with IFTTT a bit to get error logs to my email. You
Might be able to work down that line. Ultimately. It would be nice to see the flows in real time and then be able to turn on and off rules and such. Maybe some integration for the devices themselves. Not sure what all can be done but the devs have been super helpful and responsive.

**Comment by LordNex** [comment]
You might be able to tie into the API that its on the dish itself at dishy.Starlink.com(192.168.100.1)

I have a route statement in my firewall so I can still access the stats from the app or the webpage. I also have access to the MSP Beta that has more integrations and ability to poll info such as flows and usage. 

Let me know if there is anything I can do to help. What would be really cool is if we could build a page that shows what sats your currently connected too similar too [This Site](https://satellitemap.space/). I'm just beginning to get into coding but I have over 20 years of IT background specialization in Microsoft/Cisco networking.

**Comment by LordNex** [comment]
This can be closed. It's fully integrated now.
