### ISSUE TITLE
Issues with macOS Monterrey install

### ISSUE THREAD

**Issue by sophos-rickc** [Tysonpower/starlinkstatus#33]
Following the instructions for macOS install presented several issues I had to work around. I was able to resolve the issues I experienced with the prerequisites `go` and `grpcurl`. However, the commands provided for setting up crontab on macOS just didn't work at all.

, even prefixing the commands with `sudo`. Either I got a permission error on the crontab file or there was no error, but no crontab entry was created for the user or the system.

In the end, I was forced to start a root shell (i.e., `sudo -i`) and then edit `/private/etc/crontab` manually. This got the cron job scheduled and it began running.

Now that the cron job is running, it appears to be failing. `log show --process cron --info --debug` reports the following:

```
Filtering the log data using "process BEGINSWITH[cd] "cron""
Timestamp                       Thread     Type        Activity             PID    TTL
2022-06-15 10:15:00.035107-0600 0xdf8b1    Info        0x0                  13991  0    cron: (/opt/repos/Tysonpower/starlinkstatus/starlinkstatus_client.sh) CMD (-k 'XXXXX' -s -d)
2022-06-15 10:15:00.040779-0600 0xdf8b0    Info        0x0                  13990  0    cron: (/opt/repos/Tysonpower/starlinkstatus/starlinkstatus_client.sh) MAIL (mailed 105 bytes of output but got status 0x0001
```

Is the MAIL message a problem? If so, any idea how to fix that?

FWIW, here is `/etc/crontab` (which is actually, `/private/etc/crontab`):

```
8,23,38,53 * * * * /opt/repos/Tysonpower/starlinkstatus/starlinkstatus_client.sh -k XXXXX -s -d
```

> NOTE: The value of the `-k` parameter is my _*actual*_ API Key which is masked here... ;)

**Comment by Tysonpower** [comment]
Thx for the info, will test the macos setup when i got time and update the docs.
