### ISSUE TITLE
UNKNOWN_USER_CLASS_OF_SERVICE

### ISSUE THREAD

**Issue by VALarry** [Tysonpower/starlinkstatus#36]
Service Class

UNKNOWN_USER_CLASS_OF_SERVICE

Howdy, I seem to be having issues getting ping to work properly via cron on my Mac install, so I got this up and running on my Pi.  Everything seems to be working as designed, but I get the error message above.

**Comment by Tysonpower** [comment]
does this show just on the website or in the terminal as an error?
If this is shown on the website all is good, currently i see a lot of stations where dishy reports this class of service.

**Comment by VALarry** [comment]
Yes, this is in the web UI, no errors in terminal.   Thanks!

**Comment by Tysonpower** [comment]
alright, then we need to wait until every dishy shows a value that makes sense :)
