### ISSUE TITLE
Starlink Implementing Data Caps

### ISSUE THREAD

**Issue by CMDRZOD** [Tysonpower/starlinkstatus#38]
Unfortunately I'm a heavy internet user. I will have to discontinue my contribution the the starlink status. Thank you for service!

**Comment by Tysonpower** [comment]
thx, are they really doing data caps now in the us?

**Comment by CMDRZOD** [comment]
Yes just got the email. Canada & US. Copy Pasta:

To ensure our customer base is not negatively impacted by a small number of users consuming unusually high amounts of data, the Starlink team is implementing a [Fair Use policy](http://www.starlink.com/legal) in the US and Canada in December 2022.

Under the Fair Use policy, all Residential customers will receive unlimited data, and will start each month with Priority Access, which means their data usage will be prioritized during times of network congestion.
  
Customers who exceed 1 TB of data use on a monthly basis (currently < 10% of users) will automatically be switched to Basic Access for the remainder of the billing cycle, which means their data usage will be deprioritized during times of network congestion, resulting in slower speeds.

Data used between 11pm - 7am will not count towards your Priority Access.

In the last last six months, you have used over 1 TB of data during at least one month, which means you may be switched to Basic Access if your usage patterns stay the same.

Starting today, you can now monitor your data usage on your [account page](https://www.starlink.com/account/home). Read more in Starlink’s [Fair Use policy](https://www.starlink.com/legal) and in the [Terms of Service](https://www.starlink.com/legal).

You will have the option to opt-in to automatically upgrade back to Priority Access should you exceed 1 TB of data per month. 

Thank you for being an early customer and for your continued support of Starlink!

Starlink Team

**Comment by Tysonpower** [comment]
sad to see that happen, but it had to happen one day on a shared medium like a sat link. Hope you still have fun with starlink, i guess you don't have any good other connection if you use over 1TB of data a month :)

**Comment by CMDRZOD** [comment]
I'm in northern Alberta. Very rural. Only other option is LTE or dial-up.
Me and a friend live at my farm. Have many devices, consoles, camera
systems as well as a plex server.

My only hope is that my area is lightly subscribed so I hope the throttling
is light.
