### ISSUE TITLE
Average data usage

### ISSUE THREAD

**Issue by jhodges10** [Tysonpower/starlinkstatus#40]
With the new data caps being instituted, I think it would be good to add an estimate for the expected data usage to the Readme for potential users.

I've done speed tests before on 5G UWB and gone through a gigabyte of download data in 10 seconds so speed tests every 15 mins could definitely add up quickly.

**Comment by Tysonpower** [comment]
added a warning to the readme

**Comment by jhodges10** [comment]
Thanks @Tysonpower!
