### ISSUE TITLE
Key not valid 

### ISSUE THREAD

**Issue by sebalvaro** [Tysonpower/starlinkstatus#42]
I'm not sure what could be happening.
I tried with 2 keys (different stations)

```
#######:starlinkstatus:# ./starlinkstatus_client.sh -k 'xxxxxxxxxxx' -s -d
starlinkstatus.space Client - Version 1.21
API Key: xxxxxxxxxxx
Starting Ping Test (Servers: 7)...
Ping to 1.1.1.1: 35.673
Ping to tynet.eu: 346.777
Ping to fl-us-ping.vultr.com: 149.523
Ping to lax-ca-us-ping.vultr.com: 154.915
Ping to wa-us-ping.vultr.com: 196.393
Ping to tor-ca-ping.vultr.com: 169.022
Ping to syd-au-ping.vultr.com: 332.912
grpcurl dev build <no version set>
getting Dishy Data...
speedtest is running...
Request from IP: 138.x.x.x - Key not Valid...\n
```

**Comment by Tysonpower** [comment]
please send me an email to the support email so you can include your email and username, i will have a look then.

**Comment by sebalvaro** [comment]
@Tysonpower, I think I figured out the problem. My dns resolver was blocking ip-api.com/json/. So, the request was "geo:" with  empty data. (image).
<img width="399" alt="Screenshot 2022-11-23 at 09 57 49" src="https://user-images.githubusercontent.com/9834151/203552859-16e6b1e7-9ad2-4dd4-ba46-fac97e9b72d0.png">
