### ISSUE TITLE
Key not valid

### ISSUE THREAD

**Issue by sinnx3** [Tysonpower/starlinkstatus#46]
Linux script is no longer working see the following console readout:

```bash
starlinkstatus.space Client - Version 1.21
API Key: REDACTED
Starting Ping Test (Servers: 7)...
Ping to 1.1.1.1: 40.024
Ping to tynet.eu: 178.948
Ping to fl-us-ping.vultr.com: 105.599
Ping to lax-ca-us-ping.vultr.com: 128.694
Ping to wa-us-ping.vultr.com: 96.583
Ping to tor-ca-ping.vultr.com: 52.116
Ping to syd-au-ping.vultr.com: 289.869
grpcurl dev build <no version set>
getting Dishy Data...
speedtest is running...
Request from IP: REDACTED - Key not Valid...\n
sinnx3@DESKTOP-N7ML0K7:~/starlinkstatus$
```

Noteworthy mention(s): I've used a previously working API key, I've used a regenerated API key.

**Comment by 1Ale** [comment]
I have the same problem. May 7th was my last successful sent status (station 775). I tried regenerating the key, but got the same "Key not Valid...\n" error.

I can run other tests if needed.

**Comment by MXNPD** [comment]
Same issue too here, just installed in docker and keep getting key not valid, I just made an account today

**Comment by MXNPD** [comment]
@Tysonpower Any way we might be able to fix this issue? I would love to contribute my statistics to the site, but sadly cannot due to the API issue.

**Comment by Tysonpower** [comment]
Really sorry for the late reply, have a lot of other things todo currently, Starlinkstatus is just a hobby.

What version are you Running? Docker or the Script directly?

@MXNPD @sinnx3 @1Ale

**Comment by sinnx3** [comment]
> Really sorry for the late reply, have a lot of other things todo currently, Starlinkstatus is just a hobby.
> 
> What version are you Running? Docker or the Script directly?
> 
> @MXNPD @sinnx3 @1Ale 

Script directly in my case.

**Comment by Tysonpower** [comment]
> > Really sorry for the late reply, have a lot of other things todo currently, Starlinkstatus is just a hobby.
> > What version are you Running? Docker or the Script directly?
> > @MXNPD @sinnx3 @1Ale
> 
> Script directly in my case.

can you try running the script without the -d flag so no grpc is called?
