### ISSUE TITLE
Datasaver mode in docker

### ISSUE THREAD

**Issue by djrarky** [Tysonpower/starlinkstatus#47]
Hi,

I'd like to know what the default polling period is in docker, and how I can reduce / change how often speedtests are queried.

Thanks so much

**Comment by Tysonpower** [comment]
not needed anymore, no datacap now.

**Comment by djrarky** [comment]
Appreciate there's no datacap, but I don't wish to have my connection effectively hrottled so often. For that reason i won't feed data, and I can't imagine I'm the only one, 

Can you not add the frequency as an ENV variable? Would you accept a PR if I implemented that?

**Comment by Tysonpower** [comment]
will do that, good point

**Comment by Tysonpower** [comment]
Done :) You can now specify an INTERVAL in second inside the docker-compose file to set the interval. Default is 900s (15min)
