### ISSUE TITLE
SNR Statistics

### ISSUE THREAD

**Issue by sinnx3** [Tysonpower/starlinkstatus#6]
@Tysonpower @puchol SNR data becomes irrelevant (no longer provided/accessible) with Dishy Firmware update 3155b85a-29b0-4de0-8c5e-c23c321bf245.uterm.release

Source: [https://www.reddit.com/r/Starlink/comments/q8rmu3/comment/hgrgiun/?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/Starlink/comments/q8rmu3/comment/hgrgiun/?utm_source=share&utm_medium=web2x&context=3)

**Comment by Tysonpower** [comment]
Okay will remove it when all Stations are updated, next week or so i should have time.

**Comment by Tysonpower** [comment]
it's now removed
