### ISSUE TITLE
download/upload/ping Y-axis scales don't match

### ISSUE THREAD

**Issue by wfhtech** [Tysonpower/starlinkstatus#8]
The y-axis scales on the graph do not match. On the left I have 450 and 500 on the right. I assume only 1 scale is used for mbps and ms?
![image](https://user-images.githubusercontent.com/67087613/139136558-9fabc999-d1e0-46d9-b0b3-9bef93d6b525.png)

**Comment by Tysonpower** [comment]
No, it's fine, left is Mbps (0-450) and on the right is Ping in ms (0-500). I will add a lable maybe to avoid confusion in the future.

**Comment by wfhtech** [comment]
Ah, that makes sense. I thought it may be the case. A label would clarify
that.
