### ISSUE TITLE
95% and mean may not be correct?

### ISSUE THREAD

**Issue by nzkarit** [Tysonpower/starlinkstatus#9]
![image](https://user-images.githubusercontent.com/6285569/139600829-f994809c-df77-4ef2-b5cf-6e27cb7b7475.png)

With ping I would expect the 95% to be 95% of the time it should be less than X so the avg/mean should be below that number.

Likewise with upload and download I would expect 95% of the time the speed should be greater than X so the avg/mean should be above the 95% number.

Or am I reading this wrong? Or is the wrong 95% value being picked?

**Comment by Tysonpower** [comment]
will check that

**Comment by Tysonpower** [comment]
checked, should be ok
